Sprint 1 bukatuta
oier-elorrieta/E4T5 pull request #1
Opened 2024-04-23 10:26 UTC by OlandaJon

2024-04-23 12:03 UTC, OierZub requested changes

2024-04-23 12:03 UTC, OierZub commented on Erronka4/src/Modelo/Abestiak.java
> +	public Abestiak(int idMusikari, int idAudio, int iraupena, String izenburua) {
Abestiak edo abestia

2024-04-23 12:03 UTC, OierZub commented on Erronka4/src/Modelo/Artistak.java
> +public Artistak(int idArtista, String izenaArtistikoa, String deskribapena, boolean ezaugarria) {
Artistak edo artista

2024-04-23 12:03 UTC, OierZub commented on Erronka4/src/Modelo/Erabilgarriak.java
Klase hau ez litzateke modeloan egon behar.

2024-04-23 12:03 UTC, OierZub commented on Erronka4/src/Modelo/Playlistak.java
> +    public Playlistak(int idList, String izenburua, Date sorrera_data) {
Playlistak edo playlist??

2024-04-24 09:13 UTC, OierZub requested changes

2024-04-24 09:13 UTC, OierZub commented on Erronka4/src/Modelo/Abestia.java
>  	protected int IdMusikari;
atributu guztiak minuskulaz hasi behar dira... Aldatu denak

2024-04-25 11:22 UTC, oier-elorrieta requested changes
Esango nuke POJOAK falta direla, herentziak....

Zenbat main behar dituzue aplikazio batean?

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/vista/Erregistratu.java
> +	public static void main(String[] args) {
main 1

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/vista/MenuAukeraketa.java
> +	public static void main(String[] args) {
main 2

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/vista/login.java
> +	public static void main(String[] args) {
main 3

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/vista/playListMenu.java
> +	public static void main(String[] args) {
main 4

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/Kontroladorea/main.java
> +public class main {
main 5

2024-04-25 11:22 UTC, oier-elorrieta commented on Erronka4/src/Modelo/Artista.java
> +public class Artista {
Klase diagraman horrela daukazue Artista klasea?

2024-04-26 10:16 UTC, oier-elorrieta requested changes
Ziur zaudete klase diagraman adierazi zenuten guztia (POJOak) idatzita dauzkazuela?

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/DB/DBadmin.java
> +    public Connection konektatu() {
Metodo hau DBko klase guztietan errepikatzen bada, agian klase horietatik ateratzea komeni da.

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/Modelo/Abestia.java
> +	protected int idMusikari;
Zergatik protected?

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/Modelo/Hizkuntza.java
> +	protected String hizkuntzaId;
Zergatik protected?

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/Modelo/Playlist.java
> +    protected int idList;
Zergatik protected.....?

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/vista/login.java
> +	/**
Komentario horiek erabilgarriak dira?

2024-04-26 10:16 UTC, oier-elorrieta commented on Erronka4/src/vista/playListMenu.java
> +	/**
komentarioak...

2024-04-30 07:59 UTC, OierZub approved these changes
Aurrera!

2024-04-30 08:03 UTC, oier-elorrieta approved these changes

2024-04-30 08:04 UTC, merged